import { useEffect, useState } from 'react';
import { analyzeFullTestAudio, fetchSiteStatuses, fetchTestHistory, fetchTestHistoryDetail } from '../../api/buzzApi';
import { MEL_PALETTE, SignalHeatmap, SignalLineChart } from '../AIAnalysis/LiveAnalysisCharts';
import './FileTestPage.css';
import { SystemLogSection } from './SystemLogSection.jsx';
import { Pagination } from '../../components/common/Pagination';
const MFCC_PALETTE=[[30,58,138],[59,130,246],[248,250,252],[239,68,68],[153,27,27]];
const fmt=n=>Number(n||0).toFixed(1);
const rangeText=r=>`${fmt(r.startSec)}~${fmt(r.endSec)}초`;
function ChunkDetail({chunk,onClose}){if(!chunk)return null;return <div className="ft-modal" onClick={onClose}><div className="ft-modal-card" onClick={e=>e.stopPropagation()}><button className="ft-close" onClick={onClose}>×</button><h2>{rangeText(chunk)} · {chunk.prediction.label==='wasp'?'말벌':'말벌 아님'} {(chunk.prediction.confidence*100).toFixed(1)}%</h2><div className="ft-charts"><article><h3>Waveplot</h3><SignalLineChart xValues={chunk.waveform.time} yValues={chunk.waveform.amplitude} symmetric color="#2563eb" label="Wave"/></article><article><h3>FFT Spectrum</h3><SignalLineChart xValues={chunk.fft.frequency} yValues={chunk.fft.magnitudeDb} color="#0ea5e9" label="FFT"/></article><article className="wide"><h3>Mel-Spectrogram</h3><SignalHeatmap matrix={chunk.spectrogram.db} palette={MEL_PALETTE} label="Mel"/></article><article className="wide"><h3>MFCC</h3><SignalHeatmap matrix={chunk.mfcc.coefficients} palette={MFCC_PALETTE} symmetric label="MFCC"/></article></div></div></div>}
export function FileTestPage(){
 const [file,setFile]=useState(null),[site,setSite]=useState(1),[sites,setSites]=useState([]),[loading,setLoading]=useState(false),[result,setResult]=useState(null),[history,setHistory]=useState([]),[historyTotal,setHistoryTotal]=useState(0),[selectedRun,setSelectedRun]=useState(null),[chunk,setChunk]=useState(null),[error,setError]=useState(''),[page,setPage]=useState(1);
 const loadHistory=()=>fetchTestHistory(10,(page-1)*10).then(data=>{setHistory(data.items);setHistoryTotal(data.total)}).catch(()=>{}); useEffect(()=>{void loadHistory();},[page]);
 useEffect(()=>{fetchSiteStatuses().then(rows=>{setSites(rows);setSite(current=>rows.some(item=>item.site_id===current)?current:rows[0]?.site_id||1)}).catch(()=>{})},[]);
 const analyze=async()=>{if(!file)return;setLoading(true);setError('');try{const r=await analyzeFullTestAudio(file,site);setResult(r);setSelectedRun(r);await loadHistory();}catch(e){setError(e.message)}finally{setLoading(false)}};
 const run=selectedRun||result;
 const pageCount=Math.max(1,Math.ceil(historyTotal/10));const currentPage=Math.min(page,pageCount);const openHistory=async item=>{setError('');try{setSelectedRun(await fetchTestHistoryDetail(item.testId))}catch(e){setError(e.message)}};
 return <div className="ft-page"><header><p>FILE TEST MODE</p><h1>전체 음원 2초 단위 AI 테스트</h1><span>파일의 처음부터 끝까지 실제 CNN 모델로 분석하고 말벌 감지 구간을 병합합니다.</span></header>
 <section className="ft-upload"><div><label>사업장<select value={site} onChange={e=>setSite(Number(e.target.value))}>{sites.map(item=><option key={item.site_id} value={item.site_id}>{item.site_name}</option>)}</select></label><label className="ft-file"><input type="file" accept=".wav,.mp3,audio/*" onChange={e=>setFile(e.target.files?.[0]||null)}/><b>{file?.name||'WAV / MP3 파일 선택'}</b><span>최대 30MB · 마지막 2초 미만 자동 padding</span></label></div><button disabled={!file||loading} onClick={analyze}>{loading?'전체 구간 분석 중…':'전체 파일 분석'}</button>{error&&<p className="ft-error">{error}</p>}</section>
 {result&&<section className={`ft-summary ${result.finalResult==='wasp'?'danger':''}`}><div><span>최종 결과</span><strong>{result.finalResult==='wasp'?'말벌 감지':'말벌 미감지'}</strong></div><div><span>전체 길이</span><strong>{fmt(result.totalDuration)}초</strong></div><div><span>최대 confidence</span><strong>{(result.maxConfidence*100).toFixed(1)}%</strong></div><div className="ranges"><span>말벌 감지 구간</span><strong>{result.detectedRanges.length?result.detectedRanges.map(rangeText).join(' · '):'없음'}</strong></div></section>}
 <div className="ft-layout"><section className="ft-history"><h2>테스트 이력</h2>{history.length===0?<p className="ft-empty">아직 테스트 이력이 없습니다.</p>:history.map(h=><button key={h.testId} className={run?.testId===h.testId?'active':''} onClick={()=>void openHistory(h)}><div><b>{h.fileName}</b><span>{new Date(h.testedAt).toLocaleString('ko-KR')}</span></div><em className={h.finalResult==='wasp'?'danger':''}>{h.finalResult==='wasp'?'말벌 감지':'정상'}</em><small>사업장 {h.siteId} · {fmt(h.totalDuration)}초 · max {(h.maxConfidence*100).toFixed(1)}%</small></button>)}<Pagination page={currentPage} totalPages={pageCount} onChange={setPage}/></section>
 <section className="ft-chunklog"><h2>전체 chunk 로그</h2>{!run?<p className="ft-empty">테스트 이력을 선택하세요.</p>:run.chunks.map(c=><button key={c.chunkIndex} onClick={()=>setChunk(c)} className={c.prediction.label==='wasp'?'danger':''}><span>{rangeText(c)}</span><b>{c.prediction.label==='wasp'?'wasp':'normal'}</b><em>{(c.prediction.confidence*100).toFixed(1)}%</em>{c.padded&&<small>padding</small>}</button>)}</section></div>
 <SystemLogSection/><ChunkDetail chunk={chunk} onClose={()=>setChunk(null)}/></div>;
}
