import { useEffect,useState } from 'react';
import BottomNav from './BottomNav';
import { fetchLatestAnalysis, fetchSimulatorStatus, fetchSiteStatuses, startSimulator, stopSimulator } from '../api/buzzApi';
import { WaveformChart, SpectrumChart, MelSpectrogram, MfccHeatmap } from './AudioAnalysisCharts';
import './EnterpriseMobileHome.css';
const map=s=>({id:s.site_id,name:s.site_name,danger:s.status==='DANGER',label:s.detected_class,confidence:Math.round((s.confidence||0)*100),door:s.door_status});
export default function EnterpriseMobileHome({setPage}){
 const [sites,setSites]=useState([]),[selected,setSelected]=useState('all'),[sim,setSim]=useState({enabled:true,sites:{}}),[detail,setDetail]=useState(null);
 useEffect(()=>{let dead=false;const load=async()=>{try{const [a,b]=await Promise.all([fetchSiteStatuses(),fetchSimulatorStatus()]);if(!dead){setSites(a.map(map));setSim(b)}}catch{}};load();const t=setInterval(load,2000);return()=>{dead=true;clearInterval(t)}},[]);
 useEffect(()=>{if(selected==='all'){setDetail(null);return} let dead=false;const load=()=>fetchLatestAnalysis(Number(selected)).then(v=>!dead&&setDetail(v)).catch(()=>{});load();const t=setInterval(load,2000);return()=>{dead=true;clearInterval(t)}},[selected]);
 const toggle=async()=>setSim(await(sim.enabled?stopSimulator():startSimulator())); const site=sites.find(s=>s.id===Number(selected));
 return <div className="em-page"><main><header><div><small>BUZZ AI SAFETY</small><h1>실시간 모니터링</h1></div><button onClick={toggle}>{sim.enabled?'■ STOP':'▶ START'}</button></header><nav><button className={selected==='all'?'active':''} onClick={()=>setSelected('all')}>전체</button>{sites.map(s=><button className={selected===String(s.id)?'active':''} key={s.id} onClick={()=>setSelected(String(s.id))}>사업장{s.id}</button>)}</nav>
 {selected==='all'?<section className="em-sites">{sites.map(s=>{const ss=sim.sites?.[s.id];return <button key={s.id} className={s.danger?'danger':''} onClick={()=>setSelected(String(s.id))}><div><h2>{s.name}</h2><span className={s.danger?'danger':'normal'}>{s.danger?'위험':'정상'}</span></div><strong>{ss?.state==='ERROR'?'분석 오류':s.label==='wasp'?'말벌':'말벌 아님'} · {s.confidence}%</strong><small>{ss?.current_file||'음원 대기'} {Number.isInteger(ss?.chunk_index)?`#${ss.chunk_index+1}`:''}</small></button>})}</section>:site&&<section className="em-detail"><div className="em-result"><div><small>{site.name}</small><h2>{site.label==='wasp'?'말벌':'말벌 아님'}</h2></div><b>{site.confidence}%</b></div>{sim.sites?.[site.id]?.state==='ERROR'&&<p className="em-error">API 오류 · normal로 대체하지 않음</p>}{detail?<div className="em-charts"><article><h3>Waveplot</h3><WaveformChart data={detail.waveform}/></article><article><h3>FFT Spectrum</h3><SpectrumChart data={detail.fft}/></article><article><h3>Mel-Spectrogram</h3><MelSpectrogram data={detail.spectrogram}/></article>{detail.mfcc&&<article><h3>MFCC</h3><MfccHeatmap data={detail.mfcc}/></article>}</div>:<p className="em-wait">실제 2초 chunk를 기다리는 중</p>}</section>}</main><BottomNav currentPage="home" setPage={setPage}/></div>;
}
