// 결과 페이지 - 사업장별 벌 탐지 결과와 대응 상태 확인
import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useState } from 'react';
import { getLatestDetection, getSiteRuntimeStatus } from '../types';
import BottomNav from './BottomNav';
import Icon from './Icon';
const RESULTS = [
    { id: 1, time: '09:42:15', site: '사업장 3', insect: 'wasps', status: 'danger', confidence: 96, count: 1, gateAction: '개폐기 자동 차단', gateStatus: '차단' },
    { id: 2, time: '09:31:05', site: '사업장 1', insect: null, status: 'normal', confidence: 12, count: 0, gateAction: '이상 없음', gateStatus: '개방' },
    { id: 3, time: '09:25:00', site: '사업장 2', insect: null, status: 'normal', confidence: 8, count: 0, gateAction: '이상 없음', gateStatus: '개방' },
];
export default function ResultPage({ setPage }) {
    const latestDetection = getLatestDetection();
    const site3Danger = getSiteRuntimeStatus(3) === 'danger';
    const results = RESULTS.map(result => result.id === 1
        ? {
            ...result,
            time: latestDetection?.time ?? result.time,
            status: site3Danger ? 'danger' : 'normal',
            insect: site3Danger ? 'wasps' : null,
            count: site3Danger ? (latestDetection?.count ?? 1) : 0,
            confidence: site3Danger ? (latestDetection?.confidence ?? 96) : 0,
            gateAction: site3Danger ? '개폐기 자동 차단' : '이상 없음',
            gateStatus: site3Danger ? '차단' : '개방',
        }
        : result);
    const [selectedId, setSelectedId] = useState(1);
    const selected = results.find(result => result.id === selectedId) ?? results[0];
    const [toast, setToast] = useState(false);
    const sendAlert = () => {
        setToast(true);
        setTimeout(() => setToast(false), 2200);
    };
    const isDanger = selected.status === 'danger';
    return (_jsxs("div", { className: "min-h-screen bg-[#0A0E1A] pb-[calc(9rem+env(safe-area-inset-bottom))] flex flex-col", children: [toast && (_jsxs("div", { className: "fixed top-6 left-1/2 -translate-x-1/2 z-50 bg-[#1A2540] border border-white/10 text-white px-5 py-3 rounded-2xl shadow-2xl text-sm font-bold flex items-center gap-2", children: [_jsx(Icon, { name: "check", size: 18, className: "text-emerald-400", strokeWidth: 2.2 }), " \uAE34\uAE09 \uC54C\uB9BC\uC774 \uC804\uC1A1\uB418\uC5C8\uC2B5\uB2C8\uB2E4"] })), _jsxs("header", { className: "px-5 pt-6 pb-3", children: [_jsx("p", { className: "text-slate-600 text-[11px] font-semibold tracking-widest uppercase mb-0.5", children: "Detection Result" }), _jsxs("div", { className: "flex items-center justify-between", children: [_jsx("h1", { className: "text-white text-xl font-bold", children: "\uD0D0\uC9C0 \uACB0\uACFC" }), _jsxs("div", { className: "flex gap-2", children: [_jsxs("span", { className: "bg-red-500/10 border border-red-500/25 text-red-400 text-[11px] font-bold px-2.5 py-1 rounded-lg", children: ["\uC704\uD5D8 ", results.filter(r => r.status === 'danger').length, "\uAC74"] }), _jsxs("span", { className: "bg-emerald-500/10 border border-emerald-500/25 text-emerald-400 text-[11px] font-bold px-2.5 py-1 rounded-lg", children: ["\uC815\uC0C1 ", results.filter(r => r.status === 'normal').length, "\uAC74"] })] })] })] }), _jsx("div", { className: "px-5 mb-5", children: _jsx("div", { className: "grid grid-cols-2 gap-2.5", children: results.map(r => {
                        const isD = r.status === 'danger';
                        const isSel = selected.id === r.id;
                        return (_jsxs("button", { onClick: () => setSelectedId(r.id), className: `min-h-[112px] rounded-2xl p-3 border transition-all ${isSel
                                ? isD ? 'border-red-500 bg-red-500/12' : 'border-emerald-500 bg-emerald-500/12'
                                : 'border-white/6 bg-[#13192B]'}`, children: [_jsx("div", { className: `mx-auto mb-2 flex h-9 w-9 items-center justify-center rounded-xl ${isD ? 'bg-red-500/15 text-red-400' : 'bg-emerald-500/15 text-emerald-400'}`, children: _jsx(Icon, { name: isD ? 'bee' : 'check', size: 20, strokeWidth: 1.9 }) }), _jsx("p", { className: "text-white text-xs font-bold text-center", children: r.site }), _jsx("p", { className: "text-slate-600 text-[10px] text-center mb-2", children: r.time.slice(0, 5) }), _jsx("div", { className: `text-center text-[10px] font-bold py-1 rounded-lg ${isD ? 'bg-red-500/20 text-red-400' : 'bg-emerald-500/20 text-emerald-400'}`, children: isD ? '위험' : '정상' })] }, r.id));
                    }) }) }), _jsxs("div", { className: "px-5 flex-1 space-y-3", children: [_jsxs("div", { className: `relative rounded-3xl overflow-hidden border aspect-[16/9] ${isDanger ? 'border-red-500/50' : 'border-emerald-500/35'}`, children: [_jsx("img", { src: isDanger ? '/images/wasp.jpg' : '/images/honeybee.jpg', alt: "", className: "absolute inset-0 w-full h-full object-cover" }), _jsx("div", { className: `absolute inset-0 ${isDanger
                                    ? 'bg-gradient-to-t from-[#160404] via-[#0A0E1A]/55 to-transparent'
                                    : 'bg-gradient-to-t from-[#04140D] via-[#0A0E1A]/45 to-transparent'}` }), _jsxs("div", { className: "absolute top-3.5 right-3.5 w-14 h-14", children: [_jsxs("svg", { className: "w-full h-full -rotate-90", viewBox: "0 0 48 48", children: [_jsx("circle", { cx: "24", cy: "24", r: "20", fill: "#0A0E1A", fillOpacity: "0.6", stroke: "#1F2937", strokeWidth: "4" }), _jsx("circle", { cx: "24", cy: "24", r: "20", fill: "none", stroke: isDanger ? '#EF4444' : '#10B981', strokeWidth: "4", strokeLinecap: "round", strokeDasharray: `${selected.confidence / 100 * 125.6} 125.6` })] }), _jsxs("div", { className: "absolute inset-0 flex flex-col items-center justify-center", children: [_jsxs("span", { className: "text-white font-bold text-sm leading-none", children: [selected.confidence, "%"] }), _jsx("span", { className: "text-slate-400 text-[7px] mt-0.5", children: "\uC2E0\uB8B0\uB3C4" })] })] }), _jsxs("div", { className: "absolute bottom-3.5 left-4 right-4", children: [_jsxs("div", { className: "flex items-center gap-2 mb-1", children: [_jsx("span", { className: `text-base font-bold ${isDanger ? 'text-red-400' : 'text-emerald-400'}`, children: isDanger ? '말벌 침입 감지' : '정상 상태' }), _jsx("span", { className: `text-[11px] font-bold px-2 py-0.5 rounded-lg text-white ${isDanger ? 'bg-red-500' : 'bg-emerald-500'}`, children: isDanger ? '위험' : '정상' })] }), _jsxs("p", { className: "text-slate-300 text-sm", children: [selected.site, " \u00B7 ", selected.time, isDanger && ` · ${selected.count}마리`] })] })] }), _jsxs("div", { className: "bg-[#13192B] border border-white/5 rounded-2xl overflow-hidden", children: [_jsx("div", { className: "px-4 py-3 border-b border-white/5", children: _jsx("p", { className: "text-white text-sm font-bold", children: "\uD0D0\uC9C0 \uC0C1\uC138" }) }), _jsx("div", { className: "divide-y divide-white/5", children: [
                                    { label: '탐지 종류', value: isDanger ? '말벌 (Vespa)' : '없음' },
                                    { label: '탐지 수량', value: selected.count > 0 ? `${selected.count}마리` : '—' },
                                    { label: '감지 시간', value: selected.time },
                                    { label: 'AI 신뢰도', value: `${selected.confidence}%`, bar: true },
                                    { label: '판정 결과', value: isDanger ? '위험' : '정상', colored: true },
                                ].map((row, i) => (_jsxs("div", { className: "px-4 py-3 flex items-center justify-between gap-4", children: [_jsx("span", { className: "text-slate-500 text-sm", children: row.label }), _jsx("div", { className: "flex items-center gap-2", children: row.bar ? (_jsxs(_Fragment, { children: [_jsx("div", { className: "w-20 h-1.5 bg-[#0A0E1A] rounded-full overflow-hidden", children: _jsx("div", { className: `h-full rounded-full ${isDanger ? 'bg-red-500' : 'bg-emerald-500'}`, style: { width: `${selected.confidence}%` } }) }), _jsxs("span", { className: `text-sm font-bold ${isDanger ? 'text-red-400' : 'text-emerald-400'}`, children: [selected.confidence, "%"] })] })) : row.colored ? (_jsx("span", { className: `text-sm font-bold px-2.5 py-0.5 rounded-lg border ${isDanger ? 'bg-red-500/15 text-red-400 border-red-500/30' : 'bg-emerald-500/15 text-emerald-400 border-emerald-500/30'}`, children: row.value })) : (_jsx("span", { className: "text-sm font-semibold text-white", children: row.value })) })] }, i))) })] }), _jsxs("div", { className: "bg-[#13192B] border border-white/5 rounded-2xl overflow-hidden", children: [_jsxs("div", { className: "px-4 py-3 border-b border-white/5 flex items-center justify-between", children: [_jsx("p", { className: "text-white text-sm font-bold", children: "\uAC1C\uD3D0\uAE30 \uC870\uCE58" }), _jsx("button", { onClick: () => setPage('gate'), className: "text-amber-400 text-[11px] font-semibold", children: "\uC0C1\uC138\uBCF4\uAE30 \u2192" })] }), _jsxs("div", { className: "px-4 py-3.5 flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: `w-10 h-10 rounded-xl flex items-center justify-center ${selected.gateStatus === '차단' ? 'bg-red-500/20' : 'bg-emerald-500/15'}`, children: _jsx("svg", { viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: 1.8, className: `w-5 h-5 ${selected.gateStatus === '차단' ? 'text-red-400' : 'text-emerald-400'}`, children: selected.gateStatus === '차단'
                                                        ? _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", d: "M16.5 10.5V6.75a4.5 4.5 0 10-9 0v3.75m-.75 11.25h10.5a2.25 2.25 0 002.25-2.25v-6.75a2.25 2.25 0 00-2.25-2.25H6.75a2.25 2.25 0 00-2.25 2.25v6.75a2.25 2.25 0 002.25 2.25z" })
                                                        : _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", d: "M13.5 10.5V6.75a4.5 4.5 0 119 0v3.75M3.75 21.75h10.5a2.25 2.25 0 002.25-2.25v-6.75a2.25 2.25 0 00-2.25-2.25H3.75a2.25 2.25 0 00-2.25 2.25v6.75a2.25 2.25 0 002.25 2.25z" }) }) }), _jsxs("div", { children: [_jsx("p", { className: "text-white font-semibold text-sm", children: selected.gateAction }), _jsx("p", { className: "text-slate-500 text-xs", children: "\uC790\uB3D9 \uCC98\uB9AC" })] })] }), _jsx("span", { className: `text-xs font-bold px-3 py-1.5 rounded-xl border ${selected.gateStatus === '차단'
                                            ? 'bg-red-500/15 text-red-400 border-red-500/30'
                                            : 'bg-emerald-500/15 text-emerald-400 border-emerald-500/30'}`, children: selected.gateStatus })] })] }), isDanger && (_jsxs("div", { className: "bg-[#13192B] border border-white/5 rounded-2xl p-4", children: [_jsx("p", { className: "text-white text-sm font-bold mb-3", children: "\uB300\uC751 \uC808\uCC28" }), _jsx("div", { className: "space-y-2.5", children: ['즉시 현장 접근 금지', '보호 장구 착용 후 출동', '전문 방역 업체 연락'].map((a, i) => (_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("span", { className: "w-5 h-5 rounded-full bg-red-500/20 text-red-400 text-[11px] font-bold flex items-center justify-center flex-shrink-0", children: i + 1 }), _jsx("span", { className: "text-slate-300 text-sm", children: a })] }, i))) })] })), isDanger && (_jsxs("button", { onClick: sendAlert, className: "w-full py-4 bg-gradient-to-r from-red-500 to-red-600 text-white font-bold rounded-2xl shadow-lg shadow-red-500/20 active:scale-[0.98] transition-transform flex items-center justify-center gap-2", children: [_jsx("svg", { className: "w-5 h-5", fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9" }) }), "\uAE34\uAE09 \uC54C\uB9BC \uC804\uC1A1"] }))] }), _jsx(BottomNav, { currentPage: "result", setPage: setPage })] }));
}
