// 설정 페이지 - 알림·탐지 민감도·CCTV·개폐기 환경 설정
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import BottomNav from './BottomNav';
import { BuzzMark } from './Logo';
import Icon from './Icon';
export default function SettingsPage({ setPage }) {
    const [toggles, setToggles] = useState([
        { id: 'push', label: '푸시 알림', desc: '탐지 시 즉시 알림', on: true },
        { id: 'sound', label: '경보음', desc: '위험 탐지 시 소리', on: true },
        { id: 'autoRec', label: '자동 녹화', desc: '탐지 시 영상 저장', on: true },
        { id: 'autoGate', label: '자동 개폐기', desc: '탐지 시 자동 차단', on: false },
        { id: 'email', label: '이메일 알림', desc: '일일 리포트 수신', on: false },
    ]);
    const [sensitivity, setSensitivity] = useState('high');
    const [threshold, setThreshold] = useState(75);
    const toggle = (id) => setToggles(prev => prev.map(t => t.id === id ? { ...t, on: !t.on } : t));
    return (_jsxs("div", { className: "min-h-screen bg-[#0A0E1A] pb-[calc(9rem+env(safe-area-inset-bottom))] flex flex-col", children: [_jsxs("header", { className: "px-5 pt-6 pb-4", children: [_jsx("p", { className: "text-slate-500 text-xs font-medium tracking-wider uppercase mb-0.5", children: "Configuration" }), _jsx("h1", { className: "text-white text-xl font-bold", children: "\uC124\uC815" })] }), _jsxs("div", { className: "px-5 flex-1 space-y-4", children: [_jsxs("div", { className: "bg-[#13192B] border border-white/5 rounded-2xl p-4 flex items-center gap-4", children: [_jsxs("div", { className: "relative flex-shrink-0", children: [_jsx("div", { className: "absolute inset-0 bg-buzz-500/20 rounded-2xl blur-lg" }), _jsx("div", { className: "relative", children: _jsx(BuzzMark, { size: 54 }) })] }), _jsxs("div", { children: [_jsxs("div", { className: "flex items-baseline gap-2", children: [_jsx("p", { className: "font-brand text-white font-bold text-xl", style: { letterSpacing: '0.15em' }, children: "BUZZ" }), _jsx("span", { className: "text-buzz-400 text-[10px] font-bold border border-buzz-500/40 bg-buzz-500/10 px-1.5 py-0.5 rounded", style: { letterSpacing: '0.1em' }, children: "PRO" })] }), _jsx("p", { className: "text-slate-400 text-sm mt-0.5", children: "Bee Intrusion Intelligence" }), _jsx("p", { className: "text-slate-600 text-xs mt-0.5", children: "v1.0.0 \u00B7 Android" })] })] }), _jsxs("div", { className: "bg-[#13192B] border border-white/5 rounded-2xl overflow-hidden", children: [_jsx("div", { className: "px-4 py-3 border-b border-white/5", children: _jsx("p", { className: "text-white text-sm font-semibold", children: "\uC54C\uB9BC \uC124\uC815" }) }), _jsx("div", { className: "divide-y divide-white/5", children: toggles.map(t => (_jsxs("div", { className: "px-4 py-3.5 flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("p", { className: "text-white text-sm font-medium", children: t.label }), _jsx("p", { className: "text-slate-500 text-xs mt-0.5", children: t.desc })] }), _jsx("button", { onClick: () => toggle(t.id), className: `relative w-11 h-6 rounded-full transition-all duration-300 flex-shrink-0 ${t.on ? 'bg-amber-500' : 'bg-slate-700'}`, children: _jsx("div", { className: `absolute top-0.5 w-5 h-5 bg-white rounded-full shadow-md transition-all duration-300 ${t.on ? 'left-[22px]' : 'left-0.5'}` }) })] }, t.id))) })] }), _jsxs("div", { className: "bg-[#13192B] border border-white/5 rounded-2xl overflow-hidden", children: [_jsx("div", { className: "px-4 py-3 border-b border-white/5", children: _jsx("p", { className: "text-white text-sm font-semibold", children: "\uD0D0\uC9C0 \uBBFC\uAC10\uB3C4" }) }), _jsxs("div", { className: "p-4 space-y-4", children: [_jsx("div", { className: "grid grid-cols-3 gap-2", children: ([
                                            { k: 'low', label: '낮음', sub: '위험만' },
                                            { k: 'medium', label: '보통', sub: '경고 이상' },
                                            { k: 'high', label: '높음', sub: '전체 감지' },
                                        ]).map(s => (_jsxs("button", { onClick: () => setSensitivity(s.k), className: `py-3 rounded-xl text-center transition-all ${sensitivity === s.k
                                                ? 'bg-amber-500 text-white shadow-lg shadow-amber-500/20'
                                                : 'bg-[#0A0E1A] text-slate-500 border border-white/5'}`, children: [_jsx("p", { className: "font-semibold text-sm", children: s.label }), _jsx("p", { className: "text-[10px] opacity-75 mt-0.5", children: s.sub })] }, s.k))) }), _jsxs("div", { children: [_jsxs("div", { className: "flex justify-between text-xs mb-2", children: [_jsx("span", { className: "text-slate-400", children: "\uC2E0\uB8B0\uB3C4 \uC784\uACC4\uAC12" }), _jsxs("span", { className: "text-amber-400 font-semibold", children: [threshold, "%"] })] }), _jsx("input", { type: "range", min: 50, max: 99, value: threshold, onChange: e => setThreshold(+e.target.value), className: "w-full h-1.5 bg-slate-700 rounded-full appearance-none accent-amber-500 cursor-pointer" }), _jsxs("div", { className: "flex justify-between text-[10px] text-slate-600 mt-1", children: [_jsx("span", { children: "50%" }), _jsx("span", { children: "99%" })] })] })] })] }), _jsxs("div", { className: "bg-[#13192B] border border-white/5 rounded-2xl overflow-hidden", children: [_jsx("div", { className: "px-4 py-3 border-b border-white/5", children: _jsx("p", { className: "text-white text-sm font-semibold", children: "CCTV \uC124\uC815" }) }), _jsx("div", { className: "divide-y divide-white/5", children: [
                                    { label: '해상도', value: '1080p HD' },
                                    { label: '프레임 레이트', value: '30 FPS' },
                                    { label: '야간 모드', value: '자동' },
                                    { label: '녹화 저장 기간', value: '7일' },
                                ].map((row, i) => (_jsxs("div", { className: "px-4 py-3.5 flex items-center justify-between", children: [_jsx("span", { className: "text-slate-400 text-sm", children: row.label }), _jsx("span", { className: "text-white text-sm font-medium", children: row.value })] }, i))) })] }), _jsxs("div", { className: "bg-[#13192B] border border-white/5 rounded-2xl overflow-hidden", children: [_jsx("div", { className: "px-4 py-3 border-b border-white/5", children: _jsx("p", { className: "text-white text-sm font-semibold", children: "\uAC1C\uD3D0\uAE30 \uC124\uC815" }) }), _jsx("div", { className: "divide-y divide-white/5", children: [
                                    { label: '통합 개폐기', value: '사업장별 1대' },
                                ].map((row, i) => (_jsxs("div", { className: "px-4 py-3.5 flex items-center justify-between", children: [_jsx("span", { className: "text-slate-400 text-sm", children: row.label }), _jsx("span", { className: `text-xs font-semibold px-2.5 py-1 rounded-lg ${row.value === '자동 모드' ? 'bg-amber-500/20 text-amber-400' : 'bg-slate-700 text-slate-400'}`, children: row.value })] }, i))) })] }), _jsx("div", { className: "bg-[#13192B] border border-white/5 rounded-2xl overflow-hidden", children: [
                            { icon: 'history', label: '사용자 가이드' },
                            { icon: 'bell', label: '고객 지원' },
                            { icon: 'shield', label: '이용약관 · 개인정보처리방침' },
                        ].map((item, i) => (_jsxs("button", { className: `w-full px-4 py-3.5 flex items-center gap-3 active:bg-white/5 transition-colors ${i !== 2 ? 'border-b border-white/5' : ''}`, children: [_jsx(Icon, { name: item.icon, size: 19, className: "text-buzz-400", strokeWidth: 1.8 }), _jsx("span", { className: "text-white text-sm flex-1 text-left", children: item.label }), _jsx(Icon, { name: "chevron-right", size: 16, className: "text-slate-600", strokeWidth: 2 })] }, i))) }), _jsxs("p", { className: "text-center text-slate-700 text-xs pb-2", children: ["\u00A9 2024 ", _jsx("span", { className: "font-brand text-slate-500 font-bold", style: { letterSpacing: '0.15em' }, children: "BUZZ" }), " \u00B7 v1.0.0"] })] }), _jsx(BottomNav, { currentPage: "settings", setPage: setPage })] }));
}
