import { useEffect,useState } from 'react';
import { analyzeFullTestAudio, fetchHistory, fetchTestHistory } from '../api/buzzApi';
import { WaveformChart,SpectrumChart,MelSpectrogram,MfccHeatmap } from './AudioAnalysisCharts';
import { formatShortDateTime } from '../utils/formatDateTime';
import './MobileSystemLog.css';
import BottomNav from './BottomNavV2.jsx';
import './ResponsiveOverrides.css';
const fmt=value=>Number(value||0).toFixed(1);
const MobilePagination=({page,total,onChange})=>total>1?<nav className="buzz-mobile-pagination"><button disabled={page===1} onClick={()=>onChange(page-1)}>‹</button><span>{page} / {total}</span><button disabled={page===total} onClick={()=>onChange(page+1)}>›</button></nav>:null;
export default function TestPage({setPage}){
 const [file,setFile]=useState(null),[site,setSite]=useState(1),[loading,setLoading]=useState(false),[run,setRun]=useState(null),[history,setHistory]=useState([]),[logs,setLogs]=useState([]),[chunk,setChunk]=useState(null),[error,setError]=useState(''),[historyPage,setHistoryPage]=useState(1),[logPage,setLogPage]=useState(1);
 const reload=()=>Promise.allSettled([fetchTestHistory(),fetchHistory(100)]).then(([tests,system])=>{if(tests.status==='fulfilled')setHistory(tests.value);if(system.status==='fulfilled')setLogs(system.value)});useEffect(()=>{void reload();},[]);
 const analyze=async()=>{if(!file)return;setLoading(true);setError('');try{const result=await analyzeFullTestAudio(file,site);setRun(result);await reload()}catch(reason){setError(reason?.message||'테스트 분석에 실패했습니다.')}finally{setLoading(false)}};
 const historyPages=Math.max(1,Math.ceil(history.length/5)),logPages=Math.max(1,Math.ceil(logs.length/5));const currentHistoryPage=Math.min(historyPage,historyPages),currentLogPage=Math.min(logPage,logPages);const shownHistory=history.slice((currentHistoryPage-1)*5,currentHistoryPage*5),shownLogs=logs.slice((currentLogPage-1)*5,currentLogPage*5);
 return <div className="buzz-commercial-page"><main className="buzz-commercial-content buzz-test-page">
  <div className="buzz-page-heading"><h1>파일 테스트</h1><p className="buzz-page-desc">음원 파일을 2초 단위로 실제 AI 모델로 분석합니다.</p></div>
  <section className="buzz-card"><select value={site} onChange={event=>setSite(Number(event.target.value))}><option value="1">사업장 1</option><option value="2">사업장 2</option><option value="3">사업장 3</option></select><label className="buzz-file-drop"><b>{file?.name||'WAV / MP3 선택'}</b><small>최대 30MB · 마지막 2초 미만은 padding</small><input type="file" accept=".wav,.mp3,audio/*" onChange={event=>setFile(event.target.files?.[0]||null)}/></label><button className="buzz-primary-btn" disabled={!file||loading} onClick={analyze}>{loading?'분석 중…':'파일 분석'}</button>{error&&<p className="buzz-analysis-error">{error}</p>}</section>
  {run&&<section className="buzz-card"><div className="buzz-card-head"><div><p className="buzz-kicker">테스트 결과</p><h2>{run.finalResult==='wasp'?'말벌 감지':'정상'}</h2></div><strong>{(run.maxConfidence*100).toFixed(1)}%</strong></div><p>전체 {fmt(run.totalDuration)}초 · 감지 구간 {run.detectedRanges.length?run.detectedRanges.map(range=>`${fmt(range.startSec)}~${fmt(range.endSec)}초`).join(', '):'없음'}</p><div className="buzz-analysis-meta">{run.chunks.map(item=><button key={item.chunkIndex} onClick={()=>setChunk(item)}>{fmt(item.startSec)}~{fmt(item.endSec)}초 · {item.prediction.label} {(item.prediction.confidence*100).toFixed(1)}%</button>)}</div></section>}
  <section className="buzz-card"><h2>테스트 이력</h2>{shownHistory.map(item=><button className="buzz-secondary-btn" key={item.testId} onClick={()=>setRun(item)}>{item.finalResult==='wasp'?'말벌':'정상'} · {fmt(item.totalDuration)}초</button>)}<MobilePagination page={currentHistoryPage} total={historyPages} onChange={setHistoryPage}/></section>
  <section className="buzz-card buzz-mobile-system-log"><div className="buzz-card-head"><div><p className="buzz-kicker">장치·상태 동작 기록</p><h2>시스템 로그</h2></div><span className="buzz-help-pill">{logs.length}건</span></div>{logs.length?shownLogs.map((item,index)=><div className="buzz-mobile-log-row" key={item.id||index}><time>{formatShortDateTime(item.timestamp).time}</time><div><b>{item.type==='gate'?'개폐기':item.type==='recovery'?'정상 복귀':'위험 상태'}</b><small>{item.site_name||`사업장 ${item.site_id}`} · {item.action||item.title}</small></div></div>):<p className="buzz-page-desc">표시할 시스템 동작 기록이 없습니다.</p>}<MobilePagination page={currentLogPage} total={logPages} onChange={setLogPage}/></section>
 </main>{chunk&&<div className="buzz-detail-overlay" onClick={()=>setChunk(null)}><div className="buzz-history-detail buzz-analysis-modal" onClick={event=>event.stopPropagation()}><button onClick={()=>setChunk(null)}>×</button><h2>{fmt(chunk.startSec)}~{fmt(chunk.endSec)}초 상세</h2><WaveformChart data={chunk.waveform}/><MelSpectrogram data={chunk.spectrogram}/><SpectrumChart data={chunk.fft}/><MfccHeatmap data={chunk.mfcc}/></div></div>}<BottomNav currentPage="test" setPage={setPage}/></div>;
}
