import { useEffect,useState } from 'react';
import { analyzeFullTestAudio, fetchAnalysisLogs, fetchTestHistory } from '../api/buzzApi';
import { WaveformChart,SpectrumChart,MelSpectrogram,MfccHeatmap } from './AudioAnalysisCharts';
import { formatShortDateTime } from '../utils/formatDateTime';
import './MobileSystemLog.css';
import BottomNav from './BottomNav';
const fmt=value=>Number(value||0).toFixed(1);
export default function TestPage({setPage}){
 const [file,setFile]=useState(null),[site,setSite]=useState(1),[loading,setLoading]=useState(false),[run,setRun]=useState(null),[history,setHistory]=useState([]),[logs,setLogs]=useState([]),[chunk,setChunk]=useState(null),[error,setError]=useState('');
 const reload=()=>Promise.allSettled([fetchTestHistory(),fetchAnalysisLogs(20)]).then(([tests,system])=>{if(tests.status==='fulfilled')setHistory(tests.value);if(system.status==='fulfilled')setLogs(system.value)});useEffect(()=>{reload()},[]);
 const analyze=async()=>{if(!file)return;setLoading(true);setError('');try{const result=await analyzeFullTestAudio(file,site);setRun(result);await reload()}catch(reason){setError(reason?.message||'테스트 분석에 실패했습니다.')}finally{setLoading(false)}};
 return <div className="buzz-commercial-page"><main className="buzz-commercial-content buzz-test-page">
  <div className="buzz-page-heading"><h1>파일 테스트</h1><p className="buzz-page-desc">음원 파일을 2초 단위로 실제 AI 모델로 분석합니다.</p></div>
  <section className="buzz-card"><select value={site} onChange={event=>setSite(Number(event.target.value))}><option value="1">사업장 1</option><option value="2">사업장 2</option><option value="3">사업장 3</option></select><label className="buzz-file-drop"><b>{file?.name||'WAV / MP3 선택'}</b><small>최대 30MB · 마지막 2초 미만은 padding</small><input type="file" accept=".wav,.mp3,audio/*" onChange={event=>setFile(event.target.files?.[0]||null)}/></label><button className="buzz-primary-btn" disabled={!file||loading} onClick={analyze}>{loading?'분석 중…':'파일 분석'}</button>{error&&<p className="buzz-analysis-error">{error}</p>}</section>
  {run&&<section className="buzz-card"><div className="buzz-card-head"><div><p className="buzz-kicker">테스트 결과</p><h2>{run.finalResult==='wasp'?'말벌 감지':'정상'}</h2></div><strong>{(run.maxConfidence*100).toFixed(1)}%</strong></div><p>전체 {fmt(run.totalDuration)}초 · 감지 구간 {run.detectedRanges.length?run.detectedRanges.map(range=>`${fmt(range.startSec)}~${fmt(range.endSec)}초`).join(', '):'없음'}</p><div className="buzz-analysis-meta">{run.chunks.map(item=><button key={item.chunkIndex} onClick={()=>setChunk(item)}>{fmt(item.startSec)}~{fmt(item.endSec)}초 · {item.prediction.label} {(item.prediction.confidence*100).toFixed(1)}%</button>)}</div></section>}
  <section className="buzz-card"><h2>테스트 이력</h2>{history.slice(0,5).map(item=><button className="buzz-secondary-btn" key={item.testId} onClick={()=>setRun(item)}>{item.finalResult==='wasp'?'말벌':'정상'} · {fmt(item.totalDuration)}초</button>)}</section>
  <section className="buzz-card buzz-mobile-system-log"><div className="buzz-card-head"><div><p className="buzz-kicker">운영 보조 정보</p><h2>시스템 로그</h2></div><span className="buzz-help-pill">최근 20건</span></div>{logs.length?logs.map((item,index)=><div className="buzz-mobile-log-row" key={item.analysis_id||item.id||index}><time>{formatShortDateTime(item.detected_at).time}</time><div><b>{item.analysis_type==='test'?'파일 테스트':'실시간 분석'}</b><small>{item.site_id?`사업장 ${item.site_id}`:'테스트'} · {item.prediction==='wasp'?'위험':'정상'} · {(Number(item.confidence||0)*100).toFixed(1)}%</small></div></div>):<p className="buzz-page-desc">표시할 시스템 로그가 없습니다.</p>}</section>
 </main>{chunk&&<div className="buzz-detail-overlay" onClick={()=>setChunk(null)}><div className="buzz-history-detail buzz-analysis-modal" onClick={event=>event.stopPropagation()}><button onClick={()=>setChunk(null)}>×</button><h2>{fmt(chunk.startSec)}~{fmt(chunk.endSec)}초 상세</h2><WaveformChart data={chunk.waveform}/><MelSpectrogram data={chunk.spectrogram}/><SpectrumChart data={chunk.fft}/><MfccHeatmap data={chunk.mfcc}/></div></div>}<BottomNav currentPage="test" setPage={setPage}/></div>;
}
