import { useEffect,useState } from 'react';
import { analyzeFullTestAudio, fetchTestHistory } from '../api/buzzApi';
import { WaveformChart,SpectrumChart,MelSpectrogram,MfccHeatmap } from './AudioAnalysisCharts';
import BottomNav from './BottomNav';
const fmt=n=>Number(n||0).toFixed(1);
export default function TestPage({setPage}){
 const [file,setFile]=useState(null),[site,setSite]=useState(1),[loading,setLoading]=useState(false),[run,setRun]=useState(null),[history,setHistory]=useState([]),[chunk,setChunk]=useState(null),[error,setError]=useState('');
 const reload=()=>fetchTestHistory().then(setHistory).catch(()=>{});useEffect(reload,[]);
 const analyze=async()=>{if(!file)return;setLoading(true);setError('');try{const r=await analyzeFullTestAudio(file,site);setRun(r);await reload()}catch(e){setError(e.message)}finally{setLoading(false)}};
 return <div className="buzz-commercial-page"><main className="buzz-commercial-content buzz-test-page"><div className="buzz-page-heading"><h1>파일 테스트 모드</h1><p className="buzz-page-desc">전체 파일을 2초 단위로 실제 AI 모델 분석합니다.</p></div><section className="buzz-card"><select value={site} onChange={e=>setSite(Number(e.target.value))}><option value="1">사업장 1</option><option value="2">사업장 2</option><option value="3">사업장 3</option></select><label className="buzz-file-drop"><b>{file?.name||'WAV / MP3 선택'}</b><small>마지막 2초 미만은 padding</small><input type="file" accept=".wav,.mp3,audio/*" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><button className="buzz-primary-btn" disabled={!file||loading} onClick={analyze}>{loading?'전체 분석 중…':'전체 파일 분석'}</button>{error&&<p className="buzz-analysis-error">{error}</p>}</section>{run&&<section className="buzz-card"><div className="buzz-card-head"><div><p className="buzz-kicker">테스트 결과</p><h2>{run.finalResult==='wasp'?'말벌 감지':'말벌 미감지'}</h2></div><strong>{(run.maxConfidence*100).toFixed(1)}%</strong></div><p>전체 {fmt(run.totalDuration)}초</p><p>감지 구간: {run.detectedRanges.length?run.detectedRanges.map(r=>`${fmt(r.startSec)}~${fmt(r.endSec)}초`).join(', '):'없음'}</p><div className="buzz-analysis-meta">{run.chunks.map(c=><button key={c.chunkIndex} onClick={()=>setChunk(c)}>{fmt(c.startSec)}~{fmt(c.endSec)}초 · {c.prediction.label} {(c.prediction.confidence*100).toFixed(1)}%</button>)}</div></section>}<section className="buzz-card"><h2>테스트 이력</h2>{history.slice(0,10).map(h=><button className="buzz-secondary-btn" key={h.testId} onClick={()=>setRun(h)}>{h.fileName} · {h.finalResult==='wasp'?'말벌':'정상'} · {fmt(h.totalDuration)}초</button>)}</section></main>{chunk&&<div className="buzz-detail-overlay" onClick={()=>setChunk(null)}><div className="buzz-history-detail buzz-analysis-modal" onClick={e=>e.stopPropagation()}><button onClick={()=>setChunk(null)}>×</button><h2>{fmt(chunk.startSec)}~{fmt(chunk.endSec)}초 상세</h2><WaveformChart data={chunk.waveform}/><SpectrumChart data={chunk.fft}/><MelSpectrogram data={chunk.spectrogram}/><MfccHeatmap data={chunk.mfcc}/></div></div>}<BottomNav currentPage="test" setPage={setPage}/></div>;
}
