import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
// 공통 탐색 - 상단 경로와 상태 표시
import { useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { useMonitoring } from '../data/MonitoringContext';
import { BellIcon, ChevronRightIcon, PlayIcon } from './Icons';
import styles from './Topbar.module.css';
export function Topbar({ breadcrumb }) {
    const { sites, settings, detect } = useMonitoring();
    const [params] = useSearchParams();
    const [panel, setPanel] = useState(null);
    const [simulationSite, setSimulationSite] = useState('site-1');
    const [classification, setClassification] = useState('wasp');
    const [confidence, setConfidence] = useState(97);
    const alerts = settings.waspAlert ? sites.filter((site) => site.status === 'danger' && site.aiLabel === 'wasp') : [];
    return (_jsxs("header", { className: styles.topbar, children: [_jsx("div", { className: styles.breadcrumb, children: breadcrumb.map((crumb, index) => (_jsxs("span", { className: styles.crumbGroup, children: [index > 0 && _jsx(ChevronRightIcon, { size: 13, className: styles.crumbSep }), _jsx("span", { className: index === breadcrumb.length - 1 ? styles.crumbCurrent : undefined, children: crumb })] }, crumb))) }), _jsxs("div", { className: styles.actions, children: [_jsx("span", { className: styles.timestamp, children: new Date().toLocaleString('ko-KR') }), _jsxs("button", { type: "button", className: styles.simulationBadge, "aria-expanded": panel === 'simulation', onClick: () => {
                            setSimulationSite(sites.some((site) => site.id === params.get('site')) ? params.get('site') : 'site-1');
                            setPanel(panel === 'simulation' ? null : 'simulation');
                        }, children: [_jsx(PlayIcon, { size: 12 }), "\uC2DC\uBBAC\uB808\uC774\uC158"] }), _jsxs("button", { type: "button", className: styles.iconButton, "aria-label": `알림 ${alerts.length}건`, "aria-expanded": panel === 'alerts', onClick: () => setPanel(panel === 'alerts' ? null : 'alerts'), children: [_jsx(BellIcon, { size: 18 }), alerts.length > 0 && _jsx("span", { className: styles.notifDot, children: alerts.length })] }), _jsx("div", { className: styles.avatar, children: "HJ" })] }), panel === 'alerts' && _jsxs("section", { className: styles.panel, "aria-label": "\uC704\uD5D8 \uC54C\uB9BC \uBAA9\uB85D", children: [_jsxs("strong", { children: ["\uC704\uD5D8 \uC54C\uB9BC ", alerts.length, "\uAC74"] }), _jsx("button", { type: "button", onClick: () => setPanel(null), children: "\uB2EB\uAE30" }), _jsx("div", { role: "status", "aria-live": "polite", children: alerts.length === 0 ? _jsx("p", { children: settings.waspAlert ? '현재 위험 알림이 없습니다.' : '말벌 감지 알림이 꺼져 있습니다.' }) : alerts.map((site) => (_jsxs(Link, { className: styles.alertItem, to: `/?site=${site.id}`, onClick: () => setPanel(null), children: [_jsx(BellIcon, { size: 16 }), " ", site.name, " \u00B7 \uB9D0\uBC8C ", site.aiConfidence, "% \u00B7 \uC704\uD5D8"] }, site.id))) })] }), panel === 'simulation' && _jsxs("section", { className: styles.panel, "aria-label": "\uAC10\uC9C0 \uC2DC\uBBAC\uB808\uC774\uC158", children: [_jsx("strong", { children: "\uAC10\uC9C0 \uC2DC\uBBAC\uB808\uC774\uC158" }), _jsx("p", { children: "\uC0D8\uD50C \uAC10\uC9C0 \uACB0\uACFC\uB97C \uC801\uC6A9\uD569\uB2C8\uB2E4. \uC2E4\uC81C \uC7A5\uBE44\uC640 \uC5F0\uACB0\uB418\uC9C0 \uC54A\uC2B5\uB2C8\uB2E4." }), _jsxs("label", { children: ["\uC0AC\uC5C5\uC7A5 ", _jsx("select", { value: simulationSite, onChange: (e) => setSimulationSite(e.target.value), children: sites.map((site) => _jsx("option", { value: site.id, children: site.name }, site.id)) })] }), _jsxs("label", { children: ["\uAC10\uC9C0 \uC885\uB958 ", _jsxs("select", { value: classification, onChange: (e) => setClassification(e.target.value), children: [_jsx("option", { value: "wasp", children: "\uB9D0\uBC8C" }), _jsx("option", { value: "non-wasp", children: "\uB9D0\uBC8C \uC544\uB2D8" })] })] }), _jsxs("label", { children: ["\uC2E0\uB8B0\uB3C4 ", confidence, "% ", _jsx("input", { "aria-label": "\uC2DC\uBBAC\uB808\uC774\uC158 \uC2E0\uB8B0\uB3C4", type: "range", min: "0", max: "100", value: confidence, onChange: (e) => setConfidence(Number(e.target.value)) })] }), _jsx("button", { type: "button", onClick: () => { detect(simulationSite, classification, confidence); setPanel('alerts'); }, children: "\uAC10\uC9C0 \uC801\uC6A9" }), _jsx("button", { type: "button", onClick: () => setPanel(null), children: "\uB2EB\uAE30" })] }), _jsx("span", { className: styles.liveStatus, role: "status", "aria-live": "assertive", children: alerts.length > 0 ? alerts.map((site) => `${site.name} 말벌 감지 위험 알람`).join(', ') : '위험 알림 없음' })] }));
}
